name: Check JS / CSS Code Quality
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout App
      uses: actions/checkout@v2

    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install Dependencies
      run: make npm-init

    - name: Check JavaScript code
      run: make lint

    - name: Check CSS code
      run: make stylelint

